spellchecker: aspell

matrix:
- name: restructedtext
  expect_match: false
  sources:
  -
    - "**/*.rst"
    - "!**/CHANGE*"
    - "!**/change*"
    - "!**/RELEASE*"
    - "!**/release*"
    - "!**/ANNOUNCE*"
    - "!**/announce*"
    - "!**/NEWS*"
    - "!**/news*"
    - "!**/HISTORY*"
    - "!**/history*"
  hunspell:
    d: en_AU
  aspell:
    lang: en
  dictionary:
    output: build/dictionary/restructured.dic
  pipeline:
  - resplendent.filters.restructuredtext:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
  - pyspelling.filters.url:
  - unanimous.filters.nonwords:
      too_short: 3
      wordlist:
      - "**/spelling_wordlist.txt"

- name: markdown
  expect_match: false
  sources:
  -
    - "**/*.md"
    - "!**/CHANGE*"
    - "!**/change*"
    - "!**/RELEASE*"
    - "!**/release*"
    - "!**/ANNOUNCE*"
    - "!**/announce*"
    - "!**/NEWS*"
    - "!**/news*"
    - "!**/HISTORY*"
    - "!**/history*"
  hunspell:
  hunspell:
    d: en_AU
  aspell:
    lang: en
  dictionary:
    output: build/dictionary/mkdocs.dic
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
  - pyspelling.filters.url:
  - unanimous.filters.nonwords:
      too_short: 3
      wordlist:
      - "**/spelling_wordlist.txt"

- name: python
  expect_match: false
  sources:
  - "**/*.py"
  hunspell:
    d: en_AU
  aspell:
    lang: en
  dictionary:
    output: build/dictionary/python.dic
  pipeline:
  - pyspelling.filters.python:
      group_comments: true
  - pyspelling.flow_control.wildcard:
      allow:
      - py-comment
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      # Ignore lint (noqa) and coverage (pragma) as well as shebang (#!)
      - open: '^(?: *(?:noqa\b|pragma: no cover)|!)'
        close: '$'
      # Ignore Python encoding string -*- encoding stuff -*-
      - open: '^ *-\*-'
        close: '-\*-$'
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: '\\[\\`]'
      delimiters:
      # Ignore multiline content between fences (fences can have 3 or more back ticks)
      # ```
      # content
      # ```
      - open: '(?s)^(?P<open> *`{3,})$'
        close: '^(?P=open)$'
      # Ignore text between inline back ticks
      - open: '(?P<open>`+)'
        close: '(?P=open)'
  - pyspelling.filters.url:
  - unanimous.filters.nonwords:
      too_short: 3
      wordlist:
      - "**/spelling_wordlist.txt"
